name: cilium-kind

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  specs:
    name: cilium-kind
    runs-on: actuated-arm64-8cpu-16gb
    steps:
      - uses: actions/checkout@v1

      - uses: alexellis/arkade-get@master
        with:
          kind: latest
          kubectl: latest
          stern: latest
          cilium: latest
      - name: Check specs
        run: |
          sudo cp -r $HOME/.arkade/bin/* /usr/local/bin/

          curl -LO https://raw.githubusercontent.com/cilium/cilium/1.13.1/Documentation/installation/kind-config.yaml
          kind create cluster --config=kind-config.yaml

          cilium install
          cilium status --wait
          
          kubectl get pods -n kube-system

#      - name: Attach SSH
#        uses: self-actuated/connect-ssh@master
        
