name: cilium-kind

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  specs:
    name: cilium-kind
    runs-on: actuated
    steps:
      - uses: actions/checkout@v1
      - uses: alexellis/setup-arkade@master

      - uses: alexellis/arkade-get@master
        with:
          kind: latest
          kubectl: latest
          stern: latest
      - name: Check specs
        run: |
          sudo cp -r $HOME/.arkade/bin/* /usr/local/bin/

          curl -LO https://raw.githubusercontent.com/cilium/cilium/1.13.1/Documentation/installation/kind-config.yaml
          kind create cluster --config=kind-config.yaml

          CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
          CLI_ARCH=amd64
          if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
          curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
          sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
          sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
          rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}

          cilium install &
#          cilium status --wait

      - name: Attach SSH
        uses: self-actuated/connect-ssh@master
        
